//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyboardTrainer.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CharacterLower {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CharacterLower() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyboardTrainer.Resources.CharacterLower", typeof(CharacterLower).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b.
        /// </summary>
        public static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BackSpace.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c.
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Caps Lock.
        /// </summary>
        public static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на d.
        /// </summary>
        public static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        public static string D0 {
            get {
                return ResourceManager.GetString("D0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        public static string D1 {
            get {
                return ResourceManager.GetString("D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        public static string D2 {
            get {
                return ResourceManager.GetString("D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.
        /// </summary>
        public static string D3 {
            get {
                return ResourceManager.GetString("D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.
        /// </summary>
        public static string D4 {
            get {
                return ResourceManager.GetString("D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.
        /// </summary>
        public static string D5 {
            get {
                return ResourceManager.GetString("D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6.
        /// </summary>
        public static string D6 {
            get {
                return ResourceManager.GetString("D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7.
        /// </summary>
        public static string D7 {
            get {
                return ResourceManager.GetString("D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8.
        /// </summary>
        public static string D8 {
            get {
                return ResourceManager.GetString("D8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9.
        /// </summary>
        public static string D9 {
            get {
                return ResourceManager.GetString("D9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на e.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на f.
        /// </summary>
        public static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на g.
        /// </summary>
        public static string G {
            get {
                return ResourceManager.GetString("G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на h.
        /// </summary>
        public static string H {
            get {
                return ResourceManager.GetString("H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на i.
        /// </summary>
        public static string I {
            get {
                return ResourceManager.GetString("I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на j.
        /// </summary>
        public static string J {
            get {
                return ResourceManager.GetString("J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на k.
        /// </summary>
        public static string K {
            get {
                return ResourceManager.GetString("K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на l.
        /// </summary>
        public static string L {
            get {
                return ResourceManager.GetString("L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alt.
        /// </summary>
        public static string LeftAlt {
            get {
                return ResourceManager.GetString("LeftAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ctrl.
        /// </summary>
        public static string LeftCtrl {
            get {
                return ResourceManager.GetString("LeftCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift.
        /// </summary>
        public static string LeftShift {
            get {
                return ResourceManager.GetString("LeftShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Win.
        /// </summary>
        public static string LWin {
            get {
                return ResourceManager.GetString("LWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на m.
        /// </summary>
        public static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на n.
        /// </summary>
        public static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на o.
        /// </summary>
        public static string O {
            get {
                return ResourceManager.GetString("O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ;.
        /// </summary>
        public static string Oem1 {
            get {
                return ResourceManager.GetString("Oem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на `.
        /// </summary>
        public static string Oem3 {
            get {
                return ResourceManager.GetString("Oem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \.
        /// </summary>
        public static string Oem5 {
            get {
                return ResourceManager.GetString("Oem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ].
        /// </summary>
        public static string Oem6 {
            get {
                return ResourceManager.GetString("Oem6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ,.
        /// </summary>
        public static string OemComma {
            get {
                return ResourceManager.GetString("OemComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -.
        /// </summary>
        public static string OemMinus {
            get {
                return ResourceManager.GetString("OemMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [.
        /// </summary>
        public static string OemOpenBrackets {
            get {
                return ResourceManager.GetString("OemOpenBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..
        /// </summary>
        public static string OemPeriod {
            get {
                return ResourceManager.GetString("OemPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на =.
        /// </summary>
        public static string OemPlus {
            get {
                return ResourceManager.GetString("OemPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /.
        /// </summary>
        public static string OemQuestion {
            get {
                return ResourceManager.GetString("OemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;.
        /// </summary>
        public static string OemQuotes {
            get {
                return ResourceManager.GetString("OemQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на p.
        /// </summary>
        public static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на q.
        /// </summary>
        public static string Q {
            get {
                return ResourceManager.GetString("Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на r.
        /// </summary>
        public static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alt.
        /// </summary>
        public static string RightAlt {
            get {
                return ResourceManager.GetString("RightAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ctrl.
        /// </summary>
        public static string RightCtrl {
            get {
                return ResourceManager.GetString("RightCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift.
        /// </summary>
        public static string RightShift {
            get {
                return ResourceManager.GetString("RightShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Win.
        /// </summary>
        public static string RWin {
            get {
                return ResourceManager.GetString("RWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на s.
        /// </summary>
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  .
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на t.
        /// </summary>
        public static string T {
            get {
                return ResourceManager.GetString("T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tab.
        /// </summary>
        public static string Tab {
            get {
                return ResourceManager.GetString("Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на u.
        /// </summary>
        public static string U {
            get {
                return ResourceManager.GetString("U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на v.
        /// </summary>
        public static string V {
            get {
                return ResourceManager.GetString("V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на w.
        /// </summary>
        public static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на x.
        /// </summary>
        public static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на y.
        /// </summary>
        public static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на z.
        /// </summary>
        public static string Z {
            get {
                return ResourceManager.GetString("Z", resourceCulture);
            }
        }
    }
}
